Added actions to download artifact as a separate workflow

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -35,7 +35,7 @@ jobs:
 
   build:
     runs-on: ubuntu-latest
-    name: Build JAR Artifact
+    name: Build
     steps:
       - name: Setup Java JDK
         uses: actions/setup-java@v3.13.0
@@ -50,7 +50,7 @@ jobs:
       - name: Run Build
         run: mvn clean package -DskipTests
       
-      - name: Save Artifact
+      - name: Upload Artifact
         uses: actions/upload-artifact@v3
         with:
           name: maven-artifact
@@ -59,40 +59,40 @@ jobs:
           if-no-files-found: error
         
         
-  # environments-to-deploy:
-  #   runs-on: ubuntu-latest
-  #   name: Set environments to deploy
-  #   needs:
-  #     - build
-  #   outputs:
-  #     envsToDeploy: ${{ steps.envsToDeploy.outputs.result }}
-  #   env:
-  #     EVENT_NAME: ${{ github.event_name }}
-  #   steps:
-  #     - name: Set Environments to deploy
-  #       id: envsToDeploy
-  #       run: |
-  #         if [ "$EVENT_NAME" == "pull_request" ]; then
-  #           envs='["Dev"]'
-  #         elif [ "$EVENT_NAME" == "push" ]; then
-  #           envs='["Dev", "UAT"]'
-  #         else 
-  #           echo "Unable to determine Environments"
-  #           exit 1
-  #         fi
-  #         echo "result=$envs"
-  #         echo "result=$envs" >> "$GITHUB_OUTPUT"
+  environments-to-deploy:
+    runs-on: ubuntu-latest
+    name: Set environments to deploy
+    needs:
+      - build
+    outputs:
+      envsToDeploy: ${{ steps.envsToDeploy.outputs.result }}
+    env:
+      EVENT_NAME: ${{ github.event_name }}
+    steps:
+      - name: Set Environments to deploy
+        id: envsToDeploy
+        run: |
+          if [ "$EVENT_NAME" == "pull_request" ]; then
+            envs='["Dev"]'
+          elif [ "$EVENT_NAME" == "push" ]; then
+            envs='["Dev", "UAT"]'
+          else 
+            echo "Unable to determine Environments"
+            exit 1
+          fi
+          echo "result=$envs"
+          echo "result=$envs" >> "$GITHUB_OUTPUT"
       
-  # deploy-to-non-prod:
-  #   name: Deploy
-  #   needs: 
-  #     - environments-to-deploy
-  #   strategy:
-  #     fail-fast: true
-  #     max-parallel: 1
-  #     matrix:
-  #       target: ${{ fromJSON(needs.environments-to-deploy.outputs.envsToDeploy) }}
-  #   uses: ./.github/workflows/publish-and-deploy.yaml
-  #   with:
-  #     targetEnv: ${{ matrix.target }}
-  #   secrets: inherit
+  deploy-to-non-prod:
+    name: Deploy
+    needs: 
+      - environments-to-deploy
+    strategy:
+      fail-fast: true
+      max-parallel: 1
+      matrix:
+        target: ${{ fromJSON(needs.environments-to-deploy.outputs.envsToDeploy) }}
+    uses: ./.github/workflows/publish-and-deploy.yaml
+    with:
+      targetEnv: ${{ matrix.target }}
+    secrets: inherit
